build(deps): Search common paths for libz3
When trying to build 734f4f65df42179e1353489c1b0ce1b5612b2d50 on my
local MacBook (Apple Silicon M5, macOS Tahoe 26.5.1, zsh 5.9,
omz 5ef67be, rustup 1.29.0 (2026-03-05),
rustc 1.96.0 (ac68faa20 2026-05-25),
cargo 1.96.0 (30a34c682 2026-05-25)) both `make install` and `cargo
build` failed with the error message:

```
Compiling conjure-cp v0.1.0 (<path>)
error[E0463]: can't find crate for `conjure_cp_essence_macros`
  --> crates/conjure-cp/src/lib.rs:2:9
   |
 2 | pub use conjure_cp_essence_macros::*;
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^ can't find crate

For more information about this error, try `rustc --explain E0463`.
error: could not compile `conjure-cp` (lib) due to 1 previous error
`conjure-cp-essence-macros
```

This turned out to be due to `libz3.dylib` not being found in my
`DYLD_LIBRARY_PATH`, despite having both a full install of Z3 via
`brew`, as well as a copy of `libz3.dylid` from the Conjure 2.6.0 "with
solvers" install for non-Intel macOS
(https://github.com/conjure-cp/conjure/releases/tag/v2.6.0).

Manually exporting `DYLD_LIBRARY_PATH` to either of where my copies of
`libz3.dylib` was raised several permissions error dialogs on macOS.  In
the end, I found
https://doc.rust-lang.org/cargo/reference/build-scripts.html
which helped me put together the `build.rs` in this commit.

While this did fix things for me, it is entirely possible that this is
not the best solution; I am not a seasoned Rust developer.  However, as
far as I understand, the added `build.rs` should provide some sane
defaults, with people being able to symlink a local version (or put it
in a project-local `lib` directory) if they need that.  All the script
does is enumerate the usual paths and library names, and then emit some
instructions to `cargo` to include those paths when searching for the
Z3 library.

However, both Oz (ozgurakgun) and Ferdia (fmckeogh) were able to compile
the same commit on their Apple Silicon MacBooks with the same Rust
toolchain as me, so it could very well be that I missed a setup step for
dynamic libraries or similar.